# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Iman Fazel's blog
email: 4deadc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A Weblog about Linux, Programming and related stuff.
baseurl: "/4deadc.github.io" # the subpath of your site, e.g. /blog
url: "http://4deadc.github.io/" # the base hostname & protocol for your site
github_username:  4deadc

# Build settings
markdown: kramdown
